services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: start-dev --import-realm
    ports:
      - "${KEYCLOAK_PORT}:8080"  # map host 9090 to container 8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_LOGLEVEL: INFO
      KC_LOG_LEVEL: INFO
      QUARKUS_LOG_LEVEL: INFO
    volumes:
      - ./keycloak-import:/opt/keycloak/data/import