name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      TF_DIR: terraform
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_CLOUD_WORKSPACE: ${{ secrets.TF_CLOUD_WORKSPACE }}
      TF_CLOUD_SKIP_REMOTE_EXECUTION: true
      CLUSTER_NAME: spring-aks-cluster
      RESOURCE_GROUP: phone-aks-rg

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: Set up kubectl
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${RESOURCE_GROUP}
          cluster-name: ${CLUSTER_NAME }

#      - name: Replace image tag in manifest
#        run: |
#          sed -i "s|image: .*/.*|image: ${ACR_NAME}.azurecr.io/${IMAGE_NAME}:${IMAGE_TAG}|" k8s-aks/deployment.yml

      - name: Apply K8s manifests
        run: |
          kubectl apply -f k8s-aks/deployment.yml
          kubectl apply -f k8s-aks/service.yml
          kubectl apply -f k8s-aks/ingress.yml
