name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_DIR: terraform
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_CLOUD_WORKSPACE: ${{ secrets.TF_CLOUD_WORKSPACE }}
      TF_CLOUD_SKIP_REMOTE_EXECUTION: true

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup Terraform Backend
        id: backend
        run: |
          cat > "${TF_DIR}"/backend.tf << EOF
          terraform {
            backend "remote" {
               organization = "${TF_CLOUD_ORGANIZATION}"
          
               workspaces {
                 name = "${TF_CLOUD_WORKSPACE}"
               }
            }
          }
          EOF

      - name: Set custom TF vars
        run: |
          cat > "${TF_DIR}"/custom.auto.tfvars << EOF
          enable_app = true
          openai_api_key = ""
          EOF

      - name: ACR Deployment
        run: |
          terraform -chdir=$TF_DIR init -reconfigure
          terraform -chdir=$TF_DIR apply -auto-approve

      - name: Output
        run: |
          terraform -chdir=$TF_DIR output