name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Update ECS service to force a new deployment
      - name: Force ECS Deployment
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.ECS_SERVICE }} --force-new-deployment

      - name: Print ECS Public IP
        run: |
          echo "Fetching public IP of the ECS task..."
          PUBLIC_IP=$(aws ec2 describe-network-interfaces \
            --network-interface-ids $(
              aws ecs describe-tasks \
                --cluster ${{ secrets.ECS_CLUSTER }} \
                --tasks $(
                  aws ecs list-tasks --cluster ${{ secrets.ECS_CLUSTER }} --query 'taskArns[0]' --output text
                ) \
                --query "tasks[0].attachments[0].details[?name=='networkInterfaceId'].value" \
                --output text
            ) \
            --query "NetworkInterfaces[0].Association.PublicIp" \
            --output text
          )
          echo "App URL: http://$PUBLIC_IP:8080/phone/all"