name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_DIR: terraform
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set custom TF vars
        run: |
          cat > "${TF_DIR}"/custom.auto.tfvars << EOF
          enable_app = true
          openai_api_key = ""
          EOF

      - name: ACR Deployment
        run: |
          terraform -chdir=$TF_DIR init -reconfigure
          terraform -chdir=$TF_DIR apply -auto-approve
          terraform -chdir=$TF_DIR output