name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      # Update ECS service to force a new deployment
      - name: Force ECS Deployment
        run: |
          terraform -chdir=$TF_DIR init -reconfigure
          terraform -chdir=$TF_DIR apply -auto-approve \
            -var-file=terraform_az.tfvars \
            -var="openai_api_key=$OPENAI_API_KEY" \
            -var="enable_app=true"
          terraform -chdir=$TF_DIR output